### ISSUE TITLE
Can you make the mouths move?

### ISSUE THREAD

**Issue by TomiLikesToCode** [Interesting-exe/sponge-ai#2]

**Comment by Interesting-exe** [comment]
i only released the script here, you need to set up the scene, characters and animations on your own. If you'd like the characters to move their mouth when talking you could add code that plays an animation while the audio is playing to the method "private IEnumerator Speak(Dialogue d)"

**Comment by NJWXCentral** [comment]
@TomiLikesToCode were you able to get it to run?  I'm having issues.

**Comment by TomiLikesToCode** [comment]
> @TomiLikesToCode were you able to get it to run?  I'm having issues.

Haven't tried it yet.
