### ISSUE TITLE
Invalid Request Error

### ISSUE THREAD

**Issue by AnyNqm3** [Interesting-exe/sponge-ai#5]
I am getting this error:
UnityEngine.Debug:LogError (object)
OpenAI.OpenAIApi/<DispatchRequest>d__6`1<OpenAI.CreateCompletionResponse>:MoveNext () (at Library/PackageCache/com.srcnalt.openai-unity@8d6d57d5ae/Runtime/OpenAIApi.cs:88)
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()

Any Idea on how to fix it?

**Comment by Interesting-exe** [comment]
its an [OpenAI-Unity](https://github.com/srcnalt/OpenAI-Unity) error. could be an invalid api key. you should open an issue there
