### ISSUE TITLE
Scene 'SquidwardMrKrabs' couldn't be loaded because it has not been added to the build settings or the AssetBundle has not loaded

### ISSUE THREAD

**Issue by PorkDevMode** [Interesting-exe/sponge-ai#6]
It seems that it is trying to load a scene named SquidwardMrKrabs and it is sending this error in console "Scene 'SquidwardMrKrabs' couldn't be loaded because it has not been added to the build settings or the AssetBundle has not loaded".

**Comment by Interesting-exe** [comment]
change the scenes in the code to match your scenes

**Comment by PorkDevMode** [comment]
where would that be in the code?

**Comment by Interesting-exe** [comment]
https://github.com/Interesting-exe/sponge-ai/blob/master/Assets/Scripts/AIThing.cs#L208-L235

**Comment by PorkDevMode** [comment]
Wait im just blind sorry, thanks for the help.
