### ISSUE TITLE
FakeYou support?

### ISSUE THREAD

**Issue by ghost** [Interesting-exe/sponge-ai#7]
This is a big ask but if anyone could replace the uberduck api in this with [fakeyou](https://fakeyou.com/) i will love you forever, uberduck is extremely expensive in comparison to fakeyou and they both do the same thing

Theres a C# api wrapper on their discord if it helps https://discord.gg/fakeyou
(https://discord.com/channels/747997999812050946/947792035040088104/993046615164198965)

or use this link

https://cdn.discordapp.com/attachments/947792035040088104/993046615239692288/FakeYou.cs

**Comment by Interesting-exe** [comment]
i wont make it cus i made this project for shits and giggles and already lost interest in it. but the wrapper you sent is literally built for unity so it should be really easy to implement to my script

**Comment by Interesting-exe** [comment]
also i've heard that FakeYou has rate limiting so it could be pretty annoying to use with this script as it makes multiple tts requests simultaneously
