### ISSUE TITLE
Works amazingly but need resources for character movement

### ISSUE THREAD

**Issue by PorkDevMode** [Interesting-exe/sponge-ai#8]
I love this code but I was wondering if you could give me some idea / link of how to make the other characters face the character speaking when they are speaking.

**Comment by Interesting-exe** [comment]
i'd try creating a spherecast in the while statement at line [283](https://github.com/Interesting-exe/sponge-ai/blob/2378b6f68455f664323f64724863e43143989137/Assets/Scripts/AIThing.cs#L283) and making every character in the spherecast radius look at the speaker using [[Transform](https://docs.unity3d.com/ScriptReference/Transform.html).LookAt](https://docs.unity3d.com/ScriptReference/Transform.LookAt.html)
